#!/usr/bin/env bash
# Script that redirects 301 to custom page
sudo apt-get -y install nginx
sudo touch /usr/share/nginx/html/redirect_me
sudo sed -i "26 i \ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
