#!/usr/bin/env bash
# Script that configures nginx server to have a custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i "26i error_page 404 /404.html;\n location = /404.html {\n root /usr/share/nginx/html;\n internal;}\n" /etc/nginx/sites-available/default;
sudo service nginx restart
