#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive
sudo mysqldump -u root -p"$1" --all-databases > backup.sql
sudo tar -zcvf "$(date '+%m-%d-%Y').tar.gz" backup.sql
