#!/usr/bin/env bash
# Configures domain zone so that the subdomain www points to the load-balancer IP (lb-01)
# shellcheck disable=SC2086

subdomain="$2"
sub_domains=(www lb-01 web-01 web-02)

if [ -z "$2" ]
    then
        for ele in "${sub_domains[@]}"; do
            dig "${ele}.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4 " " $5}' | while read record ip_address
                do
                    echo "The subdomain ${ele} is a $record record and points to $ip_address"
                done
        done
else 
    dig "${subdomain}.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4 " " $5}' | while read record ip_address
        do
            echo "The subdomain $subdomain is a $record record and points to $ip_address"
        done
fi

