#!/usr/bin/env bash
# Script that displays To infinity and beyond with a sleep 2 between each iteration. Displays I am invincible!!! when receiving a SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
while (( 42 ))
do
	echo "To infinity and beyond"
	sleep 2
done
