#!/usr/bin/env bash
# Script that prints numbers from 1 to 100. If divisible by 3, print Fizz, if divisible by 5 print Buzz, if divisible by 3 and 5 print FizzBuzz
n=1
while (( n <= 100 ))
do
    if (( n % 15 == 0 )); then
        echo 'FizzBuzz'
    elif (( n % 5 == 0 )); then
        echo 'Buzz'
    elif (( n % 3 == 0 )); then
        echo 'Fizz'
    else
        echo $n;
    fi
    (( n++ ))
done
