#!/usr/bin/env bash
#script that prints Holberton School 10 times. On the 9th iteration, displays Hi
i=0
while ((i < 10))
do
	echo "Holberton School"
	((i++))
	if ((i == 9))
		then echo "Hi"
	fi
done
