#!/usr/bin/env bash
#script that loops from 1 to 10. On the 4th loop, prints bad luck, on the 8th loop prints good luck, otherwise Holberton School
i=0
while ((i < 10))
do	
	((i++))
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
done
