#!/usr/bin/env bash
#script that displays numbers 1 to 20. On the 4th loop, prints bad luck from China, on the 9th loop, bad luck from Japan, on the 17th loop, bad luck from Italy, else the number
i=1
while((i < 21))
do
	case $i in
	5)
		echo "bad luck from China"
		echo "$i"
	;;
	10)
	 	echo "bad luck from Japan"
		echo "$i"
	;;
	18)
		echo "bad luck from Italy"
		echo "$i"
	;;
	*)
		echo "$i"
	;;
	esac
	((i++))
done
