#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes.
hours=0
minutes=1
while ((hours <= 12))
do
	minutes=1
	echo "Hour: $hours"
	((hours++))
	while ((minutes < 60))
	do
		echo "$minutes"
		((minutes++))
	done
done
