#!/usr/bin/env bash
#Bash that displays the content of the current directory in list format where the only part of the name after the first dash is displayed
for files in *
do
	echo "$files" | cut -d "-" -f 2
done
