#!/usr/bin/env bash
#Script that gives information about the holbertonschool file in the current directory
dir="holbertonschool"
if [ -e "$dir" ]
then
	echo "holbertonschool file exists"
	if [ -s "$dir" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi

	if [ -f "$dir" ]
	then
		echo "holbertonschool file is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
	fi
