#!/usr/bin/env bash
# Script that configures an Ubuntu server where localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
sudo cp etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/    127.0.0.2/' ~/hosts.new
sudo sed -i '2i 8.8.8.8     facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
