#!/usr/bin/env bash
# Script that configures an Ubuntu server where localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
sudo sed -i '2i 8.8.8.8 facebook.com' /etc/hosts
