#!/usr/bin/env bash
# Changes access from root to nginx and listens on port 8080
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "4 i\user nginx;" /etc/nginx/nginx.conf
kill -9 `ps -A | grep apache | awk '{print $1}'`
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
