#!/usr/bin/env bash
# Changes access from root to nginx and listens on port 8080
sed -i "4i user nginx;" /etc/nginx/nginx.conf
apt-get install psmisc
killall apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
service nginx restart
